// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kiwiDeal.Listings.Infrastructure.Persistence;

#nullable disable

namespace kiwiDeal.Listings.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ListingsDbContext))]
    partial class ListingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kiwiDeal.Listings.Domain.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("starting_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_listings_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_listings_status");

                    b.ToTable("listings", "listings");
                });

            modelBuilder.Entity("kiwiDeal.Listings.Domain.Entities.Listing", b =>
                {
                    b.OwnsMany("kiwiDeal.Listings.Domain.ValueObjects.ListingImage", "Images", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("url");

                            b1.Property<Guid>("listing_id")
                                .HasColumnType("uuid")
                                .HasColumnName("listing_id");

                            b1.HasKey("id")
                                .HasName("pk_listing_images");

                            b1.HasIndex("listing_id")
                                .HasDatabaseName("ix_listing_images_listing_id");

                            b1.ToTable("listing_images", "listings");

                            b1.WithOwner()
                                .HasForeignKey("listing_id")
                                .HasConstraintName("fk_listing_images_listings");
                        });

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
