// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kiwiDeal.Auctions.Infrastructure.Persistence;

#nullable disable

namespace kiwiDeal.Auctions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuctionsDbContext))]
    [Migration("20260527001319_InitialAuctions")]
    partial class InitialAuctions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kiwiDeal.Auctions.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentHighestBid")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_highest_bid");

                    b.Property<Guid?>("CurrentHighestBidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_highest_bidder_id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_time");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_time");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("starting_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_auctions_listing_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_auctions_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_auctions_status");

                    b.ToTable("auctions", "auctions");
                });

            modelBuilder.Entity("kiwiDeal.Auctions.Domain.Entities.Auction", b =>
                {
                    b.OwnsMany("kiwiDeal.Auctions.Domain.Entities.AuctionBid", "Bids", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<Guid>("BidderId")
                                .HasColumnType("uuid")
                                .HasColumnName("bidder_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("created_at");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("auction_id")
                                .HasColumnType("uuid")
                                .HasColumnName("auction_id");

                            b1.HasKey("Id")
                                .HasName("pk_auction_bids");

                            b1.HasIndex("auction_id")
                                .HasDatabaseName("ix_auction_bids_auction_id");

                            b1.ToTable("auction_bids", "auctions");

                            b1.WithOwner()
                                .HasForeignKey("auction_id")
                                .HasConstraintName("fk_auction_bids_auctions");
                        });

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
